FROM alpine:3.21.3

RUN apk add python3 py3-pip bash

RUN mkdir -p /opt/hql
COPY . /opt/hql
WORKDIR /opt/hql

RUN pip3 install --break-system-packages -r ./requirements.txt

RUN addgroup -S hql && adduser -S hql -G hql && id hql
RUN chown -R hql:hql /opt/hql

USER hql

RUN chmod +x /opt/hql/entry.sh && ls -lh /opt/hql/entry.sh

ENTRYPOINT [ "/bin/bash", "/opt/hql/entry.sh" ]